version: '3.8'

networks:
    flavio-resume-network:
        driver: bridge

volumes:
    db_data:

services:
    app:
        build:
            context: ./backend/docker
            dockerfile: Dockerfile
        container_name: flavio-resume-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./backend:/var/www
        networks:
            - flavio-resume-network
        env_file:
            - ./.env

    frontend:
        image: node:14-alpine
        container_name: flavio-resume-frontend
        working_dir: /app
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "9087:9087"
        command: sh -c "npm install && npm run serve -- --host 0.0.0.0 --port 9087"
        networks:
            - flavio-resume-network

    postgres:
        image: postgres:13.4
        container_name: flavio-resume-postgres
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - flavio-resume-network
        ports:
            - "5432:5432"
        restart: unless-stopped

    nginx-backend:
        image: nginx:stable-alpine
        container_name: flavio-resume-nginx-backend
        ports:
            - "8087:80"
        volumes:
            - ./backend:/var/www
            - ./backend/docker/nginx:/etc/nginx/conf.d
            - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - flavio-resume-network

    swagger:
        image: swaggerapi/swagger-ui
        container_name: flavio-resume-swagger
        environment:
            SWAGGER_JSON: /usr/share/nginx/html/swagger/api-docs.json
        volumes:
            - ./docker/nginx/swagger:/usr/share/nginx/html/swagger
        ports:
            - "9080:8080"
        networks:
            - flavio-resume-network
        restart: unless-stopped