version: '3.8'

networks:
    flavio-resume-network:
        driver: bridge

volumes:
    db_data:

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: flavio-resume-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - flavio-resume-network
        env_file:
            - ./.env

    postgres:
        image: postgres:13.4
        container_name: flavio-resume-postgres
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - flavio-resume-network
        ports:
            - "5432:5432"
        restart: unless-stopped

    nginx:
        image: nginx:stable-alpine
        container_name: flavio-resume-nginx
        ports:
            - "8082:80"
            - "444:443"
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - flavio-resume-network

    swagger:
        image: swaggerapi/swagger-ui
        container_name: flavio-resume-swagger
        environment:
            SWAGGER_JSON: /usr/share/nginx/html/swagger/api-docs.json
        volumes:
            - ./docker/nginx/swagger:/usr/share/nginx/html/swagger
        ports:
            - "9080:8080"
        networks:
            - flavio-resume-network
        restart: unless-stopped
 
